# -*- coding: utf-8 -*-
"""Project Power BI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xSSIjq-s9lqueA5-HKX4_oPNV1RFJhG

# Project Power BI

Downloads historical financial data and saves in a csv file in order to be used as a dataset for Power BI.
"""

# =============================================================================
# STOCK MARKET DASHBOARD — DATA EXTRACTION SCRIPT
# Purpose  : Fetch top 25 S&P 500 stocks by market cap and save them as CSVs
# Output   : stock_prices.csv, fundamentals.csv, dim_stock.csv
# Data Source : Yahoo Finance (via yfinance) + Wikipedia
# =============================================================================


# Import the tools
import yfinance as yf          # Fetches stock data from Yahoo Finance
import pandas as pd            # Lets us work with data in table format (like Excel)
import requests                # Lets us visit websites and download their content
from io import StringIO        # Converts raw text into a format pandas can read
from datetime import datetime, timedelta  # Gives us access to today's date


# 1. GET THE LIST OF ALL S&P 500 COMPANIES FROM WIKIPEDIA


print("Step 1: Fetching S&P 500 company list from Wikipedia...")

# Wikipedia blocks automated scripts by default
# So we pretend to be a real browser by sending a browser-style header
# This is called a "User-Agent" and it tells the website what kind of device is visiting
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )
}

# Visit the Wikipedia page that lists all S&P 500 companies
# "response" holds the entire page content (like saving a webpage)
response = requests.get(
    "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies",
    headers=headers
)

# Wikipedia has a big HTML table on that page
# pd.read_html() finds all tables on the page and returns them as a list
# [0] means "give me the first table" which is the S&P 500 company list
sp500_table = pd.read_html(StringIO(response.text))[0]

# The Wikipedia table has many columns we don't need
# We only keep: ticker symbol, company name, sector, and industry
sp500_table = sp500_table[["Symbol", "Security", "GICS Sector", "GICS Sub-Industry"]]

# Rename columns to friendlier names that are easier to work with
sp500_table.columns = ["Ticker", "CompanyName", "Sector", "Industry"]

# Wikipedia uses dots in some tickers (Like BRK.B)
# But Yahoo Finance uses dashes (e.g. BRK-B)
# So we fix all dots to dashes to make sure our data fetching works correctly
sp500_table["Ticker"] = sp500_table["Ticker"].str.replace(".", "-", regex=False)

print(f"  Done! Total companies found: {len(sp500_table)}")


# 2. FETCH MARKET CAP FOR EVERY S&P 500 COMPANY


print("\nStep 2: Fetching market cap for all tickers (this may take 2-3 minutes)...")

# We will store each company's market cap here as we loop through them
market_caps = []

# Loop through every ticker in the S&P 500 list one by one
# enumerate() gives us both the index number (i) and the ticker value
for i, ticker in enumerate(sp500_table["Ticker"].tolist()):

    try:
        # Ask Yahoo Finance for all available info about this company
        # .info returns a dictionary with things like market cap, PE ratio, etc.
        info = yf.Ticker(ticker).info

        # Save the ticker and its market cap to our list
        # If market cap is not available, use 0 as a fallback
        market_caps.append({
            "Ticker": ticker,
            "Market Cap": info.get("marketCap", 0)
        })

    except Exception as e:
        # If Yahoo Finance throws an error for any ticker, don't crash
        # Just record 0 for that ticker and move on to the next one
        market_caps.append({
            "Ticker": ticker,
            "Market Cap": 0
        })

    # Print a progress update every 50 tickers so we know it's still running
    if (i + 1) % 50 == 0:
        print(f"  Processed {i + 1} of {len(sp500_table)} tickers...")

# Convert the list of dictionaries into a proper pandas table
market_cap_df = pd.DataFrame(market_caps)

print("  Done!")


# 3. PICK THE TOP 25 COMPANIES BY MARKET CAP


print("\nStep 3: Selecting top 25 companies by market cap...")

# Join the S&P 500 company info table with the market cap table
# This is like a VLOOKUP in Excel — matching rows using the Ticker column
merged = sp500_table.merge(market_cap_df, on="Ticker")

# Sort the combined table from highest market cap to lowest
merged = merged.sort_values("Market Cap", ascending=False)

# Keep only the top 25 rows (the 25 biggest companies)
# reset_index() cleans up the row numbers so they start from 0 again
top25 = merged.head(25).reset_index(drop=True)

# Extract just the ticker symbols as a plain Python list
# This is what we'll use to download prices in the next step
TICKERS = top25["Ticker"].tolist()

# Show which 25 companies were selected
print("\n  Top 25 tickers selected:")
print(top25[["Ticker", "CompanyName", "Sector", "Market Cap"]].to_string(index=False))


# 4. DOWNLOAD HISTORICAL STOCK PRICES FOR THE TOP 25


# Define the date range for price history
LOOKBACK_DAYS = 365 * 3 # Look back 3 years
END_DATE = datetime.now() # End at today's date
START_DATE = END_DATE - timedelta(days = LOOKBACK_DAYS) # Start from January 1st 2023

print(f"\nStep 4: Downloading historical prices from {START_DATE} to {END_DATE}...")

# Download daily OHLCV data for all 25 tickers at once
# OHLCV stands for: Open, High, Low, Close, Volume
raw_data = yf.download(
    tickers=TICKERS,
    start=START_DATE.strftime("%Y-%m-%d"),
    end=END_DATE.strftime("%Y-%m-%d"),
    group_by="ticker", # group_by="ticker" organizes the result by each ticker
    auto_adjust=False, # auto_adjust=False keeps the original prices without adjustments
    progress=False # progress=False hides the download progress bar
)

# The downloaded data is grouped by ticker, which is hard to use directly
# So we loop through each ticker and flatten it into one big table
all_stocks = []

for ticker in TICKERS:

    try:
        # Extract the data for this specific ticker
        df = raw_data[ticker].copy()

        # Move the Date from the index into a regular column
        df.reset_index(inplace=True)

        # Add a column so we know which ticker this row belongs to
        df["Ticker"] = ticker

        # Keep only the columns we need for Power BI
        df = df[["Date", "Ticker", "Open", "High", "Low", "Close", "Volume"]]

        # Remove any rows where the Close price is missing (data gaps)
        df.dropna(subset=["Close"], inplace=True)

        # Add this ticker's data to our collection
        all_stocks.append(df)

    except Exception as e:
        # If a ticker fails for any reason, skip it and note why
        print(f"  Skipping {ticker}: {e}")

# Stack all 25 individual tables into one big table
# ignore_index=True resets the row numbers cleanly
stock_prices_df = pd.concat(all_stocks, ignore_index=True)

# Convert the Date column to a clean date format (removes any time portion)
stock_prices_df["Date"] = pd.to_datetime(stock_prices_df["Date"]).dt.date

print(f"  Done! Total rows downloaded: {len(stock_prices_df)}")


# 5. FETCH COMPANY FUNDAMENTALS FOR THE TOP 25


print("\nStep 5: Fetching fundamentals for top 25 tickers...")

# We will store each company's fundamental data here
fundamentals = []

for ticker in TICKERS:

    try:
        # Ask Yahoo Finance for the company's general information
        info = yf.Ticker(ticker).info

        # Save the key fundamental metrics we want for the Power BI dashboard
        # If a value is not available, None is stored (shows as blank in CSV)
        fundamentals.append({
            "Ticker"         : ticker,
            "Company Name"   : info.get("longName", ""),           # Full company name
            "Market Cap"     : info.get("marketCap", None),        # Total market value
            "PE Ratio (TTM)" : info.get("trailingPE", None),       # Price to earnings ratio
            "Avg Volume (3M)": info.get("averageVolume", None)     # Average trading volume
        })

        print(f"  Fetched: {ticker}")

    except Exception as e:
        # Skip any ticker that throws an error
        print(f"  Skipping {ticker}: {e}")

# Convert the list into a pandas table
fundamentals_df = pd.DataFrame(fundamentals)

print("  Done!")


# 6. CREATE THE DIM_STOCK DIMENSION TABLE


print("\nStep 6: Building the dim_stock table...")

# Take the company metadata columns from the top 25 table
dim_stock = top25[["Ticker", "CompanyName", "Sector", "Industry"]].copy()

# Add a StockID column (1, 2, 3 ... 25) as the first column
# This acts as a unique identifier — best practice in data modeling (star schema)
dim_stock.insert(0, "StockID", range(1, len(dim_stock) + 1))

print("  Done!")


# 7. SAVE ALL THREE TABLES AS CSV FILES


print("\nStep 7: Saving CSV files...")

# Save each table as a CSV file in the current folder
# index=False means don't add an extra row number column in the file
stock_prices_df.to_csv("stock_prices.csv", index=False)   # Daily price history
fundamentals_df.to_csv("fundamentals.csv", index=False)   # Company fundamentals
dim_stock.to_csv("dim_stock.csv", index=False)             # Company dimension table

print("\n All files saved successfully:")
print("   stock_prices.csv  — Daily OHLCV price data for all 25 tickers")
print("   fundamentals.csv  — Market cap, PE ratio, avg volume per company")
print("   dim_stock.csv     — Company name, sector, industry lookup table")


# PREVIEW — Showing a sample of the output so we can quickly verify the data


print("\n--- PREVIEW: fundamentals.csv ---")
print(fundamentals_df.to_string(index=False))

print("\n--- PREVIEW: dim_stock.csv ---")
print(dim_stock.to_string(index=False))